apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-web
  name: hello-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-web
    spec:
      containers:
        - image: gcr.io/diesel-monitor-280816/github.com/jacoville/ibmlab
          imagePullPolicy: Always
          name: node-app
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-web
  name: hello-web
  namespace: default
spec:
  clusterIP: 10.15.242.246
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 31776
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: hello-web
  sessionAffinity: None
  type: LoadBalancer
